/**
 * Theme for the line-notes feature — the gutter dot, the click-to-edit tooltip
 * card with its formatting toolbar, and the read-only note block rendered
 * beneath a line. Shared by both the editing and read-only note extensions.
 */
import { EditorView } from '@codemirror/view';

export const noteTheme = EditorView.theme({
  '.cm-lineNumbers .cm-gutterElement': { cursor: 'pointer' },
  '.cm-lineNumbers .cm-gutterElement:hover': { color: 'var(--accent)' },
  '.cm-note-gutter': { width: '11px' },
  '.cm-note-gutter .cm-gutterElement': { display: 'flex', justifyContent: 'center' },
  '.cm-note-dot': {
    width: '5px',
    height: '5px',
    marginTop: '0.62em',
    borderRadius: '50%',
    background: 'var(--accent)',
    cursor: 'grab',
  },
  '.cm-note-tooltip': {
    padding: '8px',
    background: 'var(--bg)',
    border: '0.5px solid var(--border-strong)',
    borderRadius: '12px',
    boxShadow: '0 14px 34px -12px rgba(34, 28, 18, 0.34)',
  },
  '.cm-note-tools': {
    display: 'flex',
    gap: '4px',
    marginBottom: '7px',
  },
  '.cm-note-tool': {
    width: '26px',
    height: '26px',
    display: 'grid',
    placeItems: 'center',
    border: '0.5px solid var(--border)',
    borderRadius: '7px',
    background: 'var(--bg-2)',
    color: 'var(--fg-muted)',
    fontFamily: 'var(--font-sans)',
    fontSize: '13px',
    cursor: 'pointer',
  },
  '.cm-note-tool:hover': { color: 'var(--accent)', borderColor: 'var(--accent)' },
  '.cm-note-tool.is-bold': { fontWeight: '700' },
  '.cm-note-tool.is-italic': { fontStyle: 'italic', fontFamily: 'var(--font-serif)' },
  '.cm-note-tooltip textarea': {
    display: 'block',
    width: '320px',
    minHeight: '96px',
    maxHeight: '220px',
    padding: '9px 11px',
    border: '0.5px solid var(--border)',
    borderRadius: '9px',
    background: 'var(--field-bg)',
    color: 'var(--fg)',
    font: 'inherit',
    fontFamily: 'var(--font-sans)',
    fontSize: '13px',
    lineHeight: '1.55',
    resize: 'vertical',
    outline: 'none',
  },
  '.cm-note-tooltip textarea:focus': {
    borderColor: 'var(--accent)',
    boxShadow: '0 0 0 3px color-mix(in srgb, var(--accent) 14%, transparent)',
  },
  '.cm-note-foot': {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: '8px',
  },
  '.cm-note-hint': {
    fontSize: '10.5px',
    fontFamily: 'var(--font-sans)',
    color: 'var(--fg-subtle)',
  },
  '.cm-note-btns': { display: 'flex', gap: '6px' },
  '.cm-note-btn': {
    padding: '5px 12px',
    border: '0.5px solid var(--border)',
    borderRadius: '8px',
    background: 'var(--bg-2)',
    color: 'var(--fg)',
    fontFamily: 'var(--font-sans)',
    fontSize: '12px',
    fontWeight: '500',
    cursor: 'pointer',
  },
  '.cm-note-btn:hover': { borderColor: 'var(--border-strong)', background: 'var(--bg)' },
  '.cm-note-btn-primary': {
    border: '0.5px solid transparent',
    background: 'var(--accent)',
    color: '#fff',
  },
  '.cm-note-btn-primary:hover': { filter: 'brightness(1.07)', background: 'var(--accent)' },
  // Run view: a noted line is clickable; clicking opens the note card below it.
  '.cm-note-line': { cursor: 'pointer' },
  '.cm-note-line:hover': { background: 'color-mix(in srgb, var(--accent) 5%, transparent)' },
  '.cm-note-block': {
    // Spacing as padding (not margin) so the gutter stays aligned with the text.
    padding: '3px 14px 7px 36px',
  },
  '.cm-note-card': {
    background: 'var(--bg)',
    border: '0.5px solid var(--border-strong)',
    borderRadius: '11px',
    boxShadow: '0 8px 22px -12px rgba(34, 28, 18, 0.3)',
    overflow: 'hidden',
    fontFamily: 'var(--font-sans)',
  },
  '.cm-note-block-head': {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    padding: '7px 12px',
    background: 'color-mix(in srgb, var(--accent) 9%, transparent)',
    borderBottom: '0.5px solid var(--border)',
    fontSize: '9.5px',
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: '0.08em',
    color: 'var(--accent)',
  },
  '.cm-note-block-head svg': { width: '12px', height: '12px' },
  '.cm-note-block-body': {
    padding: '10px 13px',
    fontSize: '12px',
    lineHeight: '1.55',
    color: 'var(--fg)',
  },
  '.cm-note-block-body p': { margin: '0' },
  '.cm-note-block-body p + p, .cm-note-block-body p + ul, .cm-note-block-body ul + p': { marginTop: '5px' },
  '.cm-note-block-body strong': { fontWeight: '650' },
  '.cm-note-block-body em': { fontStyle: 'italic' },
  '.cm-note-block-body ul': { margin: '0', paddingLeft: '17px' },
  '.cm-note-block-body li': { marginBottom: '2px' },
  '.cm-note-block-body li::marker': { color: 'var(--accent)' },
});
